#!/usr/bin/python3
"""Factorize all the things!"""
from sys import argv


def factored_number(file):
    """read the int from the file"""
    f_array = []
    with open(file, 'r') as file:
        for line in file:
            f_array.append(int(line.strip()))
    return f_array


def factorize(integer):
    """factorize the integer"""
    factor = []
    for i in range(2, integer):
        if integer % i == 0:
            return i, integer // i
    return None, None


if __name__ == "__main__":
    if len(argv) != 2:
        exit(1)


file_name = argv[1]
arr = factored_number(file_name)
for i in arr:
    a, b = factorize(i)
    if a is not None:
        print("{}={}*{}".format(i, b, a))
